name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: e2e tests
        run: npm run test:e2e
      - name: Trigger Render Deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v

  notify_discord:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Success
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && needs.simple_deployment_pipeline.result == 'success' }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub BOT
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          severity: info
          color: '#00ff00'
          title: "A new version of Pokedex deployed"
          description: "to https://pdex.fly.dev/ by ${{ github.actor }}"
          footer: "Severity: Informational • Hoy a ${{ steps.date.outputs.time }}"
      - name: Notify Discord on Failure
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && needs.simple_deployment_pipeline.result == 'failure' }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub BOT
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          severity: error
          color: '#ff0000'
          title: "Build failed"
          description: |
            commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
          footer: "Severity: Error • Hoy a ${{ steps.date.outputs.time }}"
